### ISSUE TITLE
Rofi or dmenu selectors won't show when clipboard.json is empty

### ISSUE THREAD

**Issue by luispabon** [yory8/clipman#10]
As per title, when clipman.json is empty (or simply doesn't exist) neither selector will show. Clipman exits with status 0.

**Comment by yory8** [comment]
That's intentional. This only happens on a first install.

**Comment by yory8** [comment]
On second thought, I'll add a proper warning along with a overhaul of logging

**Comment by yory8** [comment]
Fixed in 0.9.0
