### ISSUE TITLE
Interaction with primary clipboard

### ISSUE THREAD

**Issue by yourealwaysbe** [yory8/clipman#12]
wl-paste and wl-copy both have a -p flag to allow interaction with the primary clipboard. It would be cool if clipman showed a combined history of both clipboards, and selections were sent to both (possibly optionally). This would allow data to be copied between applications that use different clipboards.

Thanks for your work. I had a brief look at doing this myself, and realised it would require a bit of refactoring / understanding of the code.

**Comment by yourealwaysbe** [comment]
I've had a play with this and discovered some issues. In particular, if you try running

    while (sleep 1); do wl-paste --primary; done

you'll notice that it messes with X applications. For example, dmenu will lose focus (irrecoverable), and keyboard scrolling in nvim-qt will pause every second. The former can be worked around by using bemenu instead, but that's not really a solution.

**Comment by yory8** [comment]
Primary clipboard will never be supported by this project because of core technical limitations (we *poll* wl-clipboard every second under the hood, rather than being notified on new events only; listening to primary clipboard events, aka selections, would be too draining)

**Comment by yory8** [comment]
Apparently, wl-clipboard will gain a --watch flag very soon, which will enable us to close issue #1 ... I'll add (optional) support for primary clipboard soon after.
