### ISSUE TITLE
Artifacts on the screen

### ISSUE THREAD

**Issue by shibumi** [yory8/clipman#14]
Hi,
when I run `clipman -d` in sway my windows start behaving weird. It looks like `clipman -d` is trying to open a new window besides my windows and is closing it all the time.. this makes clipman unusable. Do you have  any idea for this behavior? I am using the current master HEAD.

**Comment by yory8** [comment]
This looks like you are using an incorrect version of `wl-clipboard` (you need the current master HEAD for that one too).
If you are on archlinux, you can't use the one in the official repo, but the git version in AUR.

**Comment by shibumi** [comment]
Ah, I see. thanks.
