### ISSUE TITLE
Support dmenu-wayland as selector

### ISSUE THREAD

**Issue by travankor** [yory8/clipman#15]
Hi, 

Could you add support for the wayland version of dmenu?

Thanks.

https://github.com/nyyManni/dmenu-wayland

**Comment by yory8** [comment]
I just pushed a branch for it. Could you test it to see if it works?

**Comment by yory8** [comment]
I noticed that the AUR package for dmenu-wayland symlinks the binary to dmenu. I believe that this is the best approach, as users who install dmenu-wayland most likely want to use it as a drop-in replacement to dmenu.

I'll close this as a wontfix for now, and evaluate later (dmenu-wl is still an incomplete project after all, and is not even usable for our usecase of vertical alignment).
