### ISSUE TITLE
Temporary clipboard

### ISSUE THREAD

**Issue by travankor** [yory8/clipman#16]
Can clipman log entries to $XDG_RUNTIME_DIR instead of $XDG_DATA_HOME  for temporary stuff like passwords?

Also, this might be out of scope, but deleting clipboard entries with clipman+dmenu would be neat.

**Comment by yory8** [comment]
> Can clipman log entries to $XDG_RUNTIME_DIR instead of $XDG_DATA_HOME for temporary stuff like passwords?
Done in master.

> Also, this might be out of scope, but deleting clipboard entries with clipman+dmenu would be neat.

Can't do. The current implementation of the demon is not a server, so we cannot change history from other commands while the demon is running. Maybe open an issue for it, but it's low priority for me, it would require a major rewrite for little gain.

**Comment by yory8** [comment]
@travankor I implemented the clear command, available in v1.0.0-beta1!
