### ISSUE TITLE
Put top selection in the clipboard when clearing

### ISSUE THREAD

**Issue by brunelli** [yory8/clipman#25]
**How to reproduce**
- Copy `text 1` to the clipboard;
- Copy `text 2` to the clipboard`;
- Run `clipman clear` and select `text 2`.

**What I expect to happen**

`text 1` should be the current selection in the clipboard.

**What happens**

There's no selection in the clipboard.

**Comment by yory8** [comment]
Just pushed the feature to master, will test it a bit more then cut a new release
