### ISSUE TITLE
Allow infinite clipboard items

### ISSUE THREAD

**Issue by brunelli** [yory8/clipman#27]
Maybe with `--max-items=0`?

What would be the impact on performance?

**Comment by yory8** [comment]
Basically, if you copy an entire 2MB text file, your clipboard history will increase by 2MB. This has a both a storage cost and a reading/writing cost. I expect both of them to degrade quite soon with heavy usage (even if we switched to some fast compressed binary storage).

I don't think it's a good idea to promote infinite items. You could simulate it through `--max-items=999999` or something like that. It will take years of intensive copying before you reach that ceiling; even then, you'll probably not reach it because of performance

**Comment by brunelli** [comment]
> even if we switched to some fast compressed binary storage

[clipmenu](https://github.com/cdown/clipmenu)'s solution is to store the content in a separate file and have a "dictionary" with the file's hash and the preview that will be shown in dmenu.

> I don't think it's a good idea to promote infinite items

Maybe not now, but could this be revisited if/when a new storage model is implemented?

-----

Right now `--max-items=0` makes clipman do nothing. The history remains intact, but no new item is added. Couldn't this feature be implemented behind this flag (as it is common for cli tools to have `=0` mean `=inf`) but let it undocumented (use at your own risk)?

**Comment by yory8** [comment]
> clipmenu's solution is to store the content in a separate file and have a "dictionary" with the file's hash and the preview that will be shown in dmenu.
Nice idea

> Maybe not now, but could this be revisited if/when a new storage model is implemented?
There's another bottleneck we should consider: the selector. I didn't do any measuring, but I wouldn't be surprised if dmenu etc choked on large arrays. (Sure, there's `--max-items` in the selector too, but what use would it have to store stuff that we can't query?)

> Couldn't this feature be implemented behind this flag but let it undocumented
I'll implement it soon, but as an internal implementation detail, with no backwards-compatibility guarantees (for now!). Let's see how it works out in practice.

**Comment by yory8** [comment]
Done in master.

**Comment by brunelli** [comment]
> Done in master.

You're my hero.

**Comment by brunelli** [comment]
> I wouldn't be surprised if dmenu etc choked on large arrays. (Sure, there's --max-items in the selector too, but what use would it have to store stuff that we can't query?)

Well, that's something that should be solved on dmenu's side, right?

A little test with wofi shows that it lags a bit on a 6,5M, 130k lines file. With rofi I haven't seen any performance issue.

> Let's see how it works out in practice.

I'll make sure to test the cr*p out of it.

> Done in master.

You're my hero. Thank you!

**Comment by yory8** [comment]
> You're my hero. Thank you!

It was just a one line change =D

> I'll make sure to test the cr*p out of it.

The only issue I expect is performance/disk space in workflows that do lots of large copies. I guess that it's up to users to decide whether it's worth it or not for their use space.
Unless some unexpected major problem comes out, I'll end up making this official.

**Comment by brunelli** [comment]
> I guess that it's up to users to decide whether it's worth it or not for their use space

Exactly. Considering the default limit is set to 15 items, I don't think there'll be problems.
