### ISSUE TITLE
Sync clipboard at startup

### ISSUE THREAD

**Issue by brunelli** [yory8/clipman#28]
It would be nice if we had an option to sync the clipboard selection and history at startup.

My current workaround is to have `exec jq -r '. | .[-1]' ~/.local/share/clipman.json | wl-copy` in my sway config.

**Comment by yory8** [comment]
This is a good way to do it. In alternative, I could implement a `clipman sync` command to be launched at startup.

There's no other way because we run the demon through `wl-paste --watch`, so it only starts on the first *new* copy.

**Comment by yory8** [comment]
Latest master now introduces a new `clipman restore` command that serves the last available item from history.
