### ISSUE TITLE
Weird corner case with wl-copy

### ISSUE THREAD

**Issue by yory8** [yory8/clipman#35]
When copying a string *exactly* like this: `,\n,\n,\n` (it can have extra text between the characters, but the entire sequence must be present) clipman breaks (the serving-to-the-OS part, not storing the text). 
It's not wl-copy's fault because `echo ',\n,\n,\n' | wl-copy` works as expected.
Reverting bb094dab9ee025c2352bdc458e4e34be4698b2fb fixes the issue. 
I believe `strings.NewReader` might be doing something weird?

**Comment by yory8** [comment]
Minimal test case:

```
package main

import (
	"os/exec"
	"strings"
)

func main() {
	s := ",\n,\n,\n"
	c := exec.Cmd{Path: "/usr/bin/wl-copy", Stdin: strings.NewReader(s)}
	c.Run()
}
```

**Comment by yory8** [comment]
So, when feeding the stdin to wl-copy from go, it's interpreted as "application/csv", whereas if it's done from the cli, simply as text.

**Comment by sl424** [comment]
`echo` append a newline by default, so: `echo  -n -e ",\n,\n,\n" | wl-copy` will also be interpreted as "application/csv". 

wl-copy use xdg-mime( which runs `file --mime-type`) for infering the filetype. Maybe it can be fixed in wl-clipboard?
