### ISSUE TITLE
create man page

### ISSUE THREAD

**Issue by aviau** [yory8/clipman#38]
Hello,

It would be great if clipman included a manpage so that distributions can install it for their users.

Cheers!

**Comment by yory8** [comment]
Is it really necessary? `clipman -h` will give the same info anyway

**Comment by yory8** [comment]
IMO man pages are instruction MANuals, needed by big tools like ffmpeg only

**Comment by yory8** [comment]
I just noticed that you can simply run `clipman --help-man > manfile` and you get the man page. Is it fine to just add a "note for maintainers" advertising this hidden feature?

**Comment by aviau** [comment]
Leaving this note would surely be useful!

However I think that a proper manpage would contain more information such as the Usage section contained in the README.

**Comment by yory8** [comment]
Right! I'll do it manually, then.

**Comment by yory8** [comment]
Done!

**Comment by aviau** [comment]
Thank you for this!

For your information, I have uploaded clipman to Debian a few minutes ago. It should be available in the repositories soonTM (new packages take longer because they need to go trough a special process)

**Comment by yory8** [comment]
Thanks! that's great news. I'll upload the readme to advertise this as soon as it's up.
