### ISSUE TITLE
Document --tool-arg option

### ISSUE THREAD

**Issue by mhdzli** [yory8/clipman#39]
Sorry to bother you.
Does the --tool-arg  with -T flag added to clipman?
If so what is the proper way of using that?
Great job and many thanks.

**Comment by yory8** [comment]
For example: `clipman pick --tool wofi -T'--prompt=my-prompt -i'`; both `--prompt` and `-i` are flags of `wofi`.
I'll add some docs.

**Comment by mhdzli** [comment]
Thanks again for this quick answer.
