### ISSUE TITLE
Support bemenu options

### ISSUE THREAD

**Issue by AdrienLemaire** [yory8/clipman#40]
Following #33

When calling clipman with tool bemenu and bemenu related options via parameter -T, the styling of bemenu is ignored (seeing bemenu's default values).
```
$ clipman pick -t bemenu -T'-b -i -n --nb "#282a2e" --nf "#de935f" --fn "pango:Noto Sans Mono 12" --hb "#373b41" --tb "#373b41" --hf "#f0c674" --tf "#f0c674"'
```

**Comment by yory8** [comment]
It's some problem with the parsing, which currently is a bit naive.

This would work: `clipman pick -t bemenu -T'-b -i -n --nb #282a2e --nf #de935f --hb #373b41 --tb #373b41 --hf #f0c674 --tf #f0c674'`.

So:

1. we don't support spaces ("pango:Noto Sans Mono 12"); this I actually knew already
2. apparently we don't support double quotes either; this won't work: `clipman pick -t bemenu -T'-b -i -n --nb "#282a2e" --nf "#de935f" --hb "#373b41" --tb "#373b41" --hf "#f0c674" --tf "#f0c674"'`; note however that you don't need quotes if there aren't spaces inside.

I definitely plan on fixing this, hopefully it won't add too much complexity

**Comment by yory8** [comment]
Fixed in master, please let me know if there are issues!
