### ISSUE TITLE
Install and run under Ubuntu

### ISSUE THREAD

**Issue by fourstepper** [yory8/clipman#44]
Hi,

I am having trouble installing this package.

I have cloned the package to my system using git and have run `git install`, but I cannot invoke clipman as an application. Perhaps this is because I added the $GOPATH into the wrong place/badly. What's the best way to do this?

When I run `go build .` and run clipman with `./clipman` everything is working well

Thanks!

**Comment by yory8** [comment]
You need to add $GOPATH/bin to your $PATH.

**Comment by fourstepper** [comment]
I am sorry for the duplicate, I am just unsure how to do that. I am not particularly experienced with go

**Comment by yory8** [comment]
https://linuxize.com/post/how-to-add-directory-to-path-in-linux/

https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path

**Comment by fourstepper** [comment]
Thanks, got it working.
