### ISSUE TITLE
Cope with Vim (and Gtk3)

### ISSUE THREAD

**Issue by yory8** [yory8/clipman#46]
Using vim to interact with external programs' copy buffers has some very annoying quirks.
While there may be some settings/plugins to deal with them from vim's side, I'm exploring some possible mitigation from our side, in the form of experimental flags in a `vim` branch.

- [x] `unix` (SHIPPED IN MASTER): this normalizes all selections to use LF line endings; modern applications change EOLs on paste to suit the document's filetype, but vim will happily corrupt the document by mixing CRLF with LF (ie when copying from firefox)
- [ ] `no-single`: this avoids storing single ASCII characters into history (ie when using `x`)

**Feedback wanted!**

**Comment by codicodi** [comment]
The vim+firefox issue (which I also experienced myself) seems to be related to https://gitlab.gnome.org/GNOME/gtk/issues/2307
It would be great if it got mitigated in clipman IMO.

**Comment by yory8** [comment]
@codicodi Thank'you very much for that link. If we call wl-paste with `-t UTF8_STRING` rather than `-t text` the issue is solved without needing anything from clipman. I'll test this. If no side-effects appear, I'll recommend it rather than merge the `--unix` flag.

**Comment by yory8** [comment]
Closing because of lack of feedback over the `no-single` option
