### ISSUE TITLE
clipman store conflict

### ISSUE THREAD

**Issue by AdrienLemaire** [yory8/clipman#47]
versions:
* sway version 1.5-7ca9ef12 (Sep  6 2020, branch 'master')
* wl-clipboard 2.0.0
* clipman 1.5.2

sway binding:

```
exec wl-paste -t text --watch clipman store
exec wl-paste -p -t text --watch clipman store --histpath="~/.local/share/clipman-primary.json"
```

## Current behavior
Selecting any text will have it copied in both `~/.local/share/clipman.json` and `~/.local/share/clipman-primary.json`
```console
$ ] ➜ diff ~/.local/share/clipman* && echo "files are identical"
files are identical
```

## Expected behavior
`~/.local/share/clipman.json` should only store CLIPBOARD selections.

## Note
It has been confirmed in https://github.com/bugaevc/wl-clipboard/issues/94 that wl-paste works as intended, and 2 different wl-paste process do not conflict with each other.

**Comment by yory8** [comment]
Thanks for reporting. I don't use that feature myself so I never noticed.

There's nothing we can do on our side, besides changing the docs.
If I understand correctly, we can either have CLIPBOARD only or both CLIPBOARD and PRIMARY mixed together. Can you confirm?

This is quite unfortunate, as PRIMARY will quickly overshadow CLIPBOARD events. We can only fix it by rewriting clipman to use the wayland API directly, but this effort is currently on hold (I don't know C and the only existing bindings, in Rust, miss some critical functionality).

**Comment by AdrienLemaire** [comment]
@yory8 actually, wl-paste works as expected. When I use 2 instances of wl-paste, one for clipboard, and one for primary, they output what they're supposed to output

![](https://i.imgur.com/VrOZAZl.png)

But with the configuration including clipman 

```
exec wl-paste -t text --watch clipman store
exec wl-paste -p -t text --watch clipman store --histpath="~/.local/share/clipman-primary.json"
```

Somehow, both clipman store json files are updated with the primary selection, which doesn't make sense.
According to @bugaevc, the bug seems to be on your side ...

**Comment by yory8** [comment]
Can you try setting the histpath explicitly for CLIPBOARD too?

**Comment by bugaevc** [comment]
> According to @bugaevc, the bug seems to be on your side ...

I was actually careful to avoid saying that. I'm only saying it doesn't seem to be on my side 😉

**Comment by AdrienLemaire** [comment]
@yory8 just tried this out, and `exec wl-paste -t text --watch clipman store --histpath="~/.local/share/clipman-clipboard.json"` gives the same result (primary selection copied to both `~/.local/share/clipman-clipboard.json` and `~/.local/share/clipman-primary.json`.

This is very strange xD

**Comment by yory8** [comment]
Baffling, I can reproduce it (both clipboard and primary are propagated to both files).
Looking at my code, I can't seem to find the cause. I'll have to look into it more.

**Comment by yory8** [comment]
Found the culprits.

1. if you copy some text after selecting it, you generate both a primary and clipboard event, so you will always have a copy of your CLIPBOARD inside PRIMARY
2. with clipman's `-P` option NOT ENABLED, every time you select something you are also copying it to CLIPBOARD, that is generating a CLIPBOARD event, so you will always have a copy of your PRIMARY inside CLIPBOARD.

Point 2 can be solved by enabling `-P` for the `wl-paste -p` command (no need for the normal one). We could add some code to allow persistence-after-exit for primary too, but I'm not sure there's much of a use case for it.

Point 1 seems more tricky.

**Comment by AdrienLemaire** [comment]
@yory8  I tried to run `wl-paste -p -t text --watch clipman -P store --histpath=~/.local/share/clipman-primary.json`, but nothing gets saved in the `clipman-primary.json` file anymore.

If that would work, Point 1 seems like a low issue that doesn't inconvenience me :)

**Comment by yory8** [comment]
`clipman store -P`, not `clipman -P store`

**Comment by AdrienLemaire** [comment]
@yory8 it works!  Thanks a lot :)
