### ISSUE TITLE
Non-canonical module name causes go get to fail

### ISSUE THREAD

**Issue by foxcpp** [yory8/clipman#5]
https://github.com/yory8/clipman/blob/eb22802789acb9fc710990742f1014144bb4c157/go.mod#L1
It should be github.com/yory8/clipman, otherwise `go get` will fail:
```
⟩ env GO111MODULE=on go get github.com/yory8/clipman
go: finding github.com/yory8/clipman v0.7.1
go: github.com/yory8/clipman@v0.7.1: parsing go.mod: unexpected module path "clipman"
go: error loading module requirements
```

Also you might want to update README since it is (almost) possible to install clipman in one command without cloning the repo.

**Comment by yory8** [comment]
Sorry for the oversight, I fixed it now, seems to work.
