### ISSUE TITLE
Pass config and style to wofi

### ISSUE THREAD

**Issue by OmegaLambda1998** [yory8/clipman#51]
How would I pass `-c ~/.config/wofi/config` and `-s ~/.config/wofi/style.css` to clipman when calling it with `-t wofi?`

**Comment by OmegaLambda1998** [comment]
Whoops, as always I figured it out shortly after asking.
`-t "$(wofi -c ~/.config/wofi/config -s ~/.config/wofi/style.css)"`

**Comment by OmegaLambda1998** [comment]
Sorry, accidentally closed

**Comment by yory8** [comment]
`--tool-args`
