### ISSUE TITLE
Issues with with bemenu positioning (`--bottom` in the default args)

### ISSUE THREAD

**Issue by kkga** [yory8/clipman#54]
Clipman [passes some hard-coded args](https://github.com/yory8/clipman/blob/master/selector.go#L42) to bemenu.

While the `--list` option makes sense, I'm not sure why the `--bottom` is needed. In my setup (probably a Wayland-specific issue), it makes the menu appear at a random position depending the list length (see below).

I'm wondering what was the reasoning behind passing `--bottom` and if there's a chance to make it optional?

https://user-images.githubusercontent.com/1460122/104086369-65078480-5268-11eb-9f78-db197051a58c.mp4

**Comment by yory8** [comment]
Fixed, thanks.
