### ISSUE TITLE
Move the default histfile to ~/.cache instead of ~/.local/share

### ISSUE THREAD

**Issue by mcepl** [yory8/clipman#56]
``$XDG_DATA_DIRS`` (which is normally ``~/.local/share`` in the home directory) should be used preferably for the long-term data, which need to be backed up. I believe the ``histfile`` is more of the ephemeral nature, and thus it should be in ``$XDG_CACHE_HOME`` (which is normally ``~/.cache`` in the home directory).

**Comment by yory8** [comment]
No. I know of some users who keep their history around forever. Others mount ~/.cache as tmpfs to be cleared out on reboot. Note that you can pass your own path through the cli.

**Comment by mcepl** [comment]
> Note that you can pass your own path through the cli.

I did, of course.
