### ISSUE TITLE
custom tool using rofi

### ISSUE THREAD

**Issue by kushraj** [yory8/clipman#57]
hey, thanks for your work on implementing this, can you help me out a bit

As per the code in selector.go file, [this](https://github.com/yory8/clipman/blob/e77051c01d4cc39421e4984c620ec6bc5379cb6a/selector.go#L44) is the command which is used on using rofi as selection tool.

But when I use `clipman pick --print0 --tool=CUSTOM --tool-args="rofi -p pick -dmenu -lines 15`  in a terminal just for testing purpose, I can only see just 2 lines from clipboard. Why is that ?

I am trying to use [ulauncher-clipboard](https://github.com/friday/ulauncher-clipboard) as a custom tool for rofi and I can't figure this out.

**Comment by kushraj** [comment]
nvm, somehow its working properly now lol

**Comment by ozls** [comment]
Could you share with the class ? I'm trying to do the same 🙃

**Comment by kushraj** [comment]
with ulauncher-clipboard ? I already added the clipman plugin to it. you will have to use clipman-git for it to work.

**Comment by ozls** [comment]
Yes, I saw! I'm trying to make it work but nothing I do works. The plugin just returns "Could not load clipboard history", any tips ?

**Comment by kushraj** [comment]
make sure you have everything up and running, all this plugin does is to retrieve the entire clipboard from clipman and shows it. See whether clipman is returning data to plugin by `clipman show-history`  in terminal. also  `wl-paste -t text --watch clipman store` should be up and running, either launched by you or plugin

**Comment by ozls** [comment]
Hey! That's what I suspected, the problem was that my clipman did not have a show-history command. I installed the git version and now everything works like a charm. Thanks a lot!
