### ISSUE TITLE
Clipboard misbehaving 

### ISSUE THREAD

**Issue by kushraj** [yory8/clipman#59]
clipboard isn't working properly whenever `wl-paste -t text --watch clipman store` is running in background with both git/release version

to reproduce - 
- nautilus doesn't copy anything on first attempt, to copy/paste a file, I have to press ctrl+c  twice to get a file in clipboard

On firefox

- copy an image from a webpage , and paste it in a field ie whatsapp-web chat
- on ist copy-paste attempt, instead of image, im seeing text like `<meta http-equiv="content-type" content="text/html; charset=utf-8"><img alt="something" class="_something" src="something.jpg" style="max-height:700px">`
- on second copy/paste attempt ( copied the image again, then paste ), image is pasted successfully

can you see what's wrong here ?

**Comment by yory8** [comment]
Seeing that you're using nautilus, are you on gnome? clipman is not supported on gnome

**Comment by yory8** [comment]
About the firefox error, assuming you are NOT on gnome: with `wl-paste -t text --watch clipman store` not running, what's the output of `wl-paste -l` on first copy? and of `wl-paste -t text`?

**Comment by kushraj** [comment]
> Seeing that you're using nautilus, are you on gnome? clipman is not supported on gnome

I'm on sway-git

weirdly enough, there was no problem until a week ago, maybe its because of something I did but can't point at anything

there is no problem with text functionality, both primary and normal clipboard works fine 

it occurs when I copy images in browser, or files in nautilus.  copy and pasting using wl-copy/paste on a terminal works without any issue. 

But if I copy an image on browser, wl-paste > file gives `No suitable type of content copied`, and wl-paste returns same metadata as I mentioned earlier. Copying the image again and using wl-paste works fine the second and successive time.

same with nautilus, If i copy a file using ctrl+c, wl-paste > file gives a text file with name of copied file in it. 
and ctrl+v does nothing. I have to run ctrl+c twice for it to work

**Comment by yory8** [comment]
The output of `wl-paste -l` seems to mean that the issue is not in clipman. I suspect either sway-git or gtk3. Did you update them recently? if yes, I recommend trying a downgrade

**Comment by kushraj** [comment]
but its only when clipman daemon is listening, this issue occurs. otherwise everything is fine.  I downgraded both of them to earlier packages when it was working perfectly but no change

**Comment by yory8** [comment]
there was a misunderstanding then. The output of `wl-paste -l` is correct as expected if clipman is not running in the background?
What baffles me is that clipman hasn't changed in a long while, so if it was working until a week ago, it must be something in your environment that changed. When you downgraded sway, did you also downgraded wlroots?

**Comment by kushraj** [comment]
yes ofc, I downgraded both sway and wlroots to release version, and gtk to January when it was workikg properly. 

>  clipman hasn't changed in a long while

yeah, I even tried the release versuon which is lot older but still same issue. Can't figure out what it could be

**Comment by kushraj** [comment]
is it not reproducible on your side at all ?

**Comment by yory8** [comment]
Actually yes. Just tried pasting here in this field, first time I get the html, second time it tries (and fails) to upload the image. To fix the issue you need to change the command to `wl-paste -t text --watch clipman store -P`.

When you copy an image, firefox offers both the image and some html metadata. wl-paste receives the text and clipman replaces the entire clipboard with it (if you don't use `-P`). The second time the text is the same, so clipman ignores it and exits, without overwriting the clipboard.

This is yet again our old problem that we don't support non-text mimetypes, which conflicts with persistence. 
I've considered dropping persistence by default, as it's always causing some new problem, but it would mean breaking backwards compatibility.

**Comment by ErikReider** [comment]
I'm also experiencing this issue with clipman... Works as intended with the -P argument but that defeats the whole purpose of even using clipman (retain clipboard on program close) for me...

**Comment by yory8** [comment]
@ErikReider  Unfortunately there's no way around it.

**Comment by sl424** [comment]
How about we add a timestamp to every offer? When firefox offers the data and metadata, we can compare the time and reject the metadata?

**Comment by djvs** [comment]
Same issue here.  Was this ever fixed?
