### ISSUE TITLE
Carriage returns upset clipman

### ISSUE THREAD

**Issue by bhepple** [yory8/clipman#68]
```
$ echo -e "\rfoo" |wl-copy < /dev/stdin 
$ clipman pick -t wofi # and pick the foo item
2021/06/20 10:02:50 couldn't recover original string
```
Carriage returns are not common in Unix but do sometimes crop up. Perhaps clipman should filter them out if it can't deal with them?

This is with 1.6.0

**Comment by bhepple** [comment]
Note that a workaround is to use a wrapper script around clipman - something like this in the ~/.config/sway/config file:

```
exec wl-paste -t text --watch myclipman
```

... and in the wrapper script:

```
tr -d '\r' |  clipman store
```

**Comment by yory8** [comment]
thanks
