### ISSUE TITLE
Passthrough the picker tool's exit status code

### ISSUE THREAD

**Issue by khaveesh** [yory8/clipman#71]
I'm using `wtype` tool to simulate a `Ctrl-V` event and thus make the clipboard manager provide a seamless paste experience. My binding looks like this:
    `bindsym $mod+y exec clipman pick -t bemenu -T="$bemenu_opts -p 'clip > '" && wtype -M ctrl v -m ctrl`
But clipman suppresses the exit status of the picker tool and always returns a exit code of 0. This means that I can't detect if any clipboard entry was selected or not and the && passes always.

What is the reason for not passing the status code? If it is actually necessary, could you provide a flag to disable this.

I'm not proficient in Go, but this looks like a simple enough change that I could attempt it. Would you be willing to merge it?

**Comment by yory8** [comment]
good idea, but don't pass the tool's error, they are inconsistent with each other. Rather, try to see if a simple `else { os.Exit(2) }` at https://github.com/yory8/clipman/blob/5c6734de74a9927d244247c5e8e7086be19bcbe7/main.go#L85 suits you well. (I'd like an exit code 2 rather than 1 because it's not a failure)

**Comment by khaveesh** [comment]
I wrote my own clipboard manager as an experiment.

Python for storing:
```
#!/usr/bin/python

import sys
from pathlib import PosixPath

MAX_CLIPS = 15

text = sys.stdin.read()

# Empty input
if not text:
    sys.exit()

# Escape newlines to store as a single line
text = text.replace("\\n", "\\\\n")
text = text.replace("\n", "\\n")

clipfile = PosixPath("~/.local/share/clips.txt").expanduser()

if clipfile.exists():
    clips = clipfile.read_text().splitlines()

    if text in clips:
        clips.remove(text)
    clips.insert(0, text)

    if len(sys.argv) > 1 and sys.argv[1].isdigit():
        MAX_CLIPS = int(sys.argv[1])

    if len(clips) > MAX_CLIPS:
        clips[MAX_CLIPS:] = []

else:
    clips = [text]

clipfile.write_text("\n".join(clips) + "\n")
```

And perl regex for decoding the escaped newlines:
```
#!/bin/bash
set -euf -o pipefail

bemenu_opts="-n -l 30 -P '>' --fn 'Sans 13' --scrollbar hide"

bemenu $bemenu_opts -p 'clip > ' < ~/.local/share/clips.txt |
    perl -pe 's/(?<!\\)\\n/\n/g; s/\\\\n/\\n/g' |
    wl-copy -n

wtype -M ctrl v -m ctrl
```

Meets all my needs and is very simple.
