### ISSUE TITLE
[Feature Request] Snippets and image support

### ISSUE THREAD

**Issue by wakatara** [yory8/clipman#72]
Hey @yory8

Loving using clipman with rofi. Definitely a nice replacement on wayland for greenclip in i3 (and before that, Alfred on OSX).

Two things I'd absolutely love to see which I think would make this even better for a large number of sway users:

1. A "snippets" file that can be yaml or similarly configured (ie keyword: "snippet") where we can grab multiline text that we use often 
2. Images (I think you already said no to this, but it is definitely needed for most people)

(also, would be willing to take a shot at one of these myself. Passable go, but no wayland programming experience... ). 

and thanks for writing this! I was afraid I was going to have to port greenclip... =]

**Comment by yory8** [comment]
1. doesn't need clipman.  you can use rofi + wl-paste directly with your own database!
2. no, not because i don't want it, but because it requires a full rewrite using the wlroots protocol directly, and even then it's not so trivial (also, it's not "most" people, it's quite a niche need afaik)
