### ISSUE TITLE
How to have both PRIMARY and CLIPBOARD available on middle-click?

### ISSUE THREAD

**Issue by ThomasBucaioni** [yory8/clipman#73]
It's not really an issue, but I don't know where else to ask... In my Swaywm config, I have:
```
# Regular clipboard
exec wl-paste -t text --watch clipman store

# Primary clipboard
exec wl-paste -p -t text --watch clipman store -P --histpath="~/.local/share/clipman.json"

# History display
bindsym $mod+shift+v exec clipman pick --tool wofi -T'-i'
```
With `C-v`, the merge is always used. But with middle-click, the merge doesn't work and only the primary as pasted

**Comment by yory8** [comment]
This is not the responsibility of the clipboard manager (we only deal with history). Perhaps you could try playing with wl-copy/paste (bind them to middle click in sway?)

**Comment by yory8** [comment]
Sorry, I misunderstood your question. We have the `--primary` flag that should do what you asked?

**Comment by ThomasBucaioni** [comment]
What I'm trying is to merge both clipboard, the regular one with C-c and the primary. And then recall both with the middle-click

**Comment by ThomasBucaioni** [comment]
It does, there was a mistake in my config:
```
exec wl-paste -t text --watch clipman store 
exec wl-paste -p -t text --watch clipman store -P --histpath="~/.local/share/clipman.json"
bindsym $mod+shift+v exec clipman --primary pick --tool wofi -T'-i'
```
Thank you for your help
