### ISSUE TITLE
Clipman doesn't escape carriage return when used with rofi

### ISSUE THREAD

**Issue by ptrcnull** [yory8/clipman#76]
When copying two entries with the second one having `\r\n` in the content, it displays as such:

![image](https://user-images.githubusercontent.com/26630168/144163198-ab25cb0b-e53a-49f5-a082-e4b35d4410c7.png)

EDIT: oh, it apparently [does so](https://github.com/yory8/clipman/blob/96cde32f61faaf8535d3734d29f1ef8e2f66672a/selector.go#L114) in the code, I'll add some debug prints to check why it happens then.

**Comment by ptrcnull** [comment]
...nevermind, it was fixed in literally the only commit after the last release.

**Comment by yory8** [comment]
thanks, i made a new release now
