### ISSUE TITLE
How to swap items?

### ISSUE THREAD

**Issue by mizzunet** [yory8/clipman#80]
Hi there :hand: 

I'd like to swap the latest one with the one before that.
Suppose I have clipboard items, `["3","2","1"]`, and by some command/key binding to make it  `["3","1","2"]`

Would this be possible with clipman?

This would be extremely useful when filling username and password on sites.
Currently, from password manager, 
1. first I copy the password, then the username. 
2. And from the site, I paste username (which is latest) 
3. then open the clipboard picker and choose the password and then paste it on the field

**Comment by yory8** [comment]
Unsupported
