### ISSUE TITLE
Arbitrary copy with -p flag

### ISSUE THREAD

**Issue by mshzsh** [yory8/clipman#85]
OS: Arch Linux x86_64
Kernel: 5.19.13-arch1-1
DE: Hyprland
clipman version : 1.6.1
wl-clipboard version : 2.1.0

When i use `wl-paste -p -t text --watch clipman store --max-items=2000` it arbitrarily copies whatever I select without me copying!
And if I don't use the `-p` flag, I have to copy every file twice for it to work (only files, not texts)

**Comment by yory8** [comment]
> copies whatever I select without me copying

that's how primary copy works!

> copy every file twice

what does copying a file (vs text) mean?

**Comment by mshzsh** [comment]
> that's how primary copy works!

I did not catch, When I select a text anywhere, it is automatically copied without me press `ctrl+c`, does this mean primary?!

> what does copying a file (vs text) mean?

For example, when I copy a file in Thunar, the paste button is disabled, but if I copy that file twice, the paste button is activated. Of course, this problem exists in other programs as well.

**Comment by ilkecan** [comment]
> I did not catch, When I select a text anywhere, it is automatically copied without me press `ctrl+c`, does this mean primary?!

Yes, it is automatically copied to the primary selection. You can read this for more detail: https://superuser.com/a/90357.

**Comment by yory8** [comment]
> when I copy a file in Thunar

the clipboard only deals with copy from withing a file (copy the content of the file, not the file itself). Copying a file is a completely different mechanism under the hood.
