### ISSUE TITLE
Does not detect dmenu if dmenu was compiled from source

### ISSUE THREAD

**Issue by samerickson** [yory8/clipman#9]
I am using a custom version of `dmenu` which I have compiled from source on my machine, yet `clipman` states that `dmenu` is not installed. 

## Workaround
The issue is removed if I install `dmenu` via `pacman`. 

## Suspected issue
When installed from source `dmenu` is installed to `/usr/local/bin/dmenu`. when it is installed via package manager, it is installed to `/usr/bin/dmenu`.

## Replicating issue
1. `sudo pacman -Rns dmenu`
2. `git clone git://git.suckless.org/dwm`
3. `cd dmenu && sudo make install`

**Comment by yory8** [comment]
This should not happen.
Either:

- you are using an older version of dmenu
- `/usr/local/bin/dmenu` is not in your `PATH`, so you need to add it

**Comment by samerickson** [comment]
I can confirm that `/usr/local/bin` is contained in my `PATH`, and I have `dmenu-4.9`. Which is the latest version.

**Comment by samerickson** [comment]
I should note that if I modify the way dmenu is checked for, by using the complete path, rather than: ` bin, err := exec.LookPath(tool)`. It's strange, because it should work, and I can get it to work by running the following works as expected: 
```
package main

import (
    "fmt"
    "os/exec"
)

func main() {
    path, err := exec.LookPath("bmenu")
    if err != nil {
        fmt.Println(err)
    }

    fmt.Println(path)
}
```
Apologies I do not have more experience with golang to help more with this issue.

**Comment by yory8** [comment]
What version of clipman are you using?
I tried your steps on my system and everything works correctly!

**Comment by samerickson** [comment]
Yeah, its kinda weird because the code works, but I still get this stupid error. It may be related to the fact that I am using `linux-hardened-kernel` as `/usr/local/bin` is used for user namespaces, but it is strange that running the code outside clipman still works. Either which way, thanks for looking into this.

**Comment by yory8** [comment]
I strongly suspect it's something about your configuration. I'll close this for now.
