### ISSUE TITLE
"Unsupported tool" error when attempting to run with fuzzel

### ISSUE THREAD

**Issue by lunamode** [yory8/clipman#91]
When attempting to use [fuzzel](https://codeberg.org/dnkl/fuzzel) as a picker with clipman, clipman fails with the following error:

```
2023/03/27 00:29:22 unsupported tool: fuzzel
```

[This comment](https://github.com/yory8/clipman/pull/83#issuecomment-1243288147) seems to suggest that this combo worked at some point in the past, so I'm not sure why it seems to be broken now… 🤔

Using Fedora 37 with Sway 1.7. Thanks in advance for any guidance you might be able to offer! ☺️

**Comment by yory8** [comment]
`--tool=CUSTOM --tool-args="fuzzel"`
