### ISSUE TITLE
Behaviour when clipman.json file is missing is surprising

### ISSUE THREAD

**Issue by magthe** [yory8/clipman#92]
It seems `clipman` doesn't handle it well when its files are missing.

I just installed a new system and my tried and trusted Sway config of

```
exec clipman restore
exec wl-paste -t text --watch clipman store --max-items=50
exec wl-paste -p -t text --watch clipman store -P --histpath="~/.local/share/clipman-primary.json" --max-items=50
```

didn't start working until I'd run

```
echo '[]' | .local/share/clipman-primary.json
echo '[]' > .local/share/clipman.json
```

and manually run the `wl-paste` commands once.

**Comment by yory8** [comment]
Can't reproduce. 
When I run clipman restore, I get "Nothing to restore", as expected. When I run the other commands, I get no errors and the file is created as expected.

Could you try running the commands manually, after killing all running processes and erasing the files, and see if you get some sort of errors?

**Comment by magthe** [comment]
I'm sorry but I gave up on clipman due to this issue, it also didn't seem to save anything in the files.
